### ISSUE TITLE
Add JWT Login and Signup

### ISSUE THREAD

**Issue by anasvakyathodi** [anasvakyathodi/DevPad#2]
JWT based login and signup

**Comment by ayush-git228** [comment]
can I work on this

**Comment by anasvakyathodi** [comment]
> 
> 
> can I work on this

Sure @ayush-git228 ... if you have any doubts on outcome... mention it on gitter.

**Comment by ayush-git228** [comment]
I have merged my PR. please do check it out and mention the errors (if any). Thanks

**Comment by ayush-git228** [comment]
Also isn't the repo a part of hacktoberfest, if not you can add it though, anyway no worries.

**Comment by anasvakyathodi** [comment]
> I have merged my PR. please do check it out and mention the errors (if any). Thanks

Got an error “passport-local-mongoose module not found”, also I didn’t understand how to make api call for signin... Thanks for your interest on this project :)

**Comment by ayush-git228** [comment]
PR done regarding the issue raised.

**Comment by anasvakyathodi** [comment]
> 
> 
> PR done regarding the issue raised.

![Screenshot (150)](https://user-images.githubusercontent.com/44634141/95318100-b2640680-08b3-11eb-9539-696c25e202f8.png)
![Screenshot (149)](https://user-images.githubusercontent.com/44634141/95318108-b5f78d80-08b3-11eb-8376-576dfb6054d6.png)
![Screenshot (148)](https://user-images.githubusercontent.com/44634141/95318114-b7c15100-08b3-11eb-9a3f-e7c6f5d6d44a.png)

got some errors on login .

**Comment by anasvakyathodi** [comment]
@ayush-git228 how should I pass token for logout request?

**Comment by ayush-git228** [comment]
There is no such method for logout in jwt as this tokens are made with a expiry time and they renew after the specific time or if you change the secret key. You can delete sessions and cookies. If you want to delete jwt, you can use jwt-redis module.

**Comment by anasvakyathodi** [comment]
> 
> 
> There is no such method for logout in jwt as this tokens are made with a expiry time and they renew after the specific time or if you change the secret key. You can delete sessions and cookies. If you want to delete jwt, you can use jwt-redis module.

Iam very glad to have a contributor like you... hope I could contribute your projects too soon... Thanks Buddy :)

**Comment by ayush-git228** [comment]
Glad, I'm able to help you. Will connect for a project. Stay contributing. Thanks
